"""Add 'system' column to Incident model

Revision ID: 14621c95e3ee
Revises: 347e8c39fd1b
Create Date: 2023-12-04 00:45:21.147876

"""
from alembic import op
import sqlalchemy as sa
# from sqlalchemy.orm import sessionmaker
# from app import create_app
# from app import db
# from app.models import Incident


# revision identifiers, used by Alembic.
revision = '14621c95e3ee'
down_revision = '347e8c39fd1b'
branch_labels = None
depends_on = None


# Session = sessionmaker()

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system', sa.Boolean(),
                            nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_column('system')

    # ### end Alembic commands ###
