"""convert impact version

Revision ID: 34f7ab360a3a
Revises: 3c893bcfb35b
Create Date: 2023-04-04 15:58:24.636670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34f7ab360a3a'
down_revision = '3c893bcfb35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.alter_column('impact',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.SmallInteger(),
               existing_nullable=True,
               postgresql_using="impact::smallint")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.alter_column('impact',
               existing_type=sa.SmallInteger(),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    # ### end Alembic commands ###
