"""empty message

Revision ID: 61e73167c986
Revises: 
Create Date: 2023-03-15 15:07:52.714777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e73167c986'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_component_id'), ['id'], unique=False)

    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('impact', sa.Enum('maintenance', 'minor', 'major', 'outage', name='incidentimpactenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_id'), ['id'], unique=False)

    op.create_table('component_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id', 'name', name='u_attr_comp')
    )
    with op.batch_alter_table('component_attribute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_component_attribute_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_component_attribute_id'), ['id'], unique=False)

    op.create_table('incident_component_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_component_relation', schema=None) as batch_op:
        batch_op.create_index('inc_comp_rel', ['incident_id', 'component_id'], unique=False)

    op.create_table('incident_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_status_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_status_incident_id'), ['incident_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_status_incident_id'))
        batch_op.drop_index(batch_op.f('ix_incident_status_id'))

    op.drop_table('incident_status')
    with op.batch_alter_table('incident_component_relation', schema=None) as batch_op:
        batch_op.drop_index('inc_comp_rel')

    op.drop_table('incident_component_relation')
    with op.batch_alter_table('component_attribute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_component_attribute_id'))
        batch_op.drop_index(batch_op.f('ix_component_attribute_component_id'))

    op.drop_table('component_attribute')
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_id'))

    op.drop_table('incident')
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_component_id'))

    op.drop_table('component')
    # ### end Alembic commands ###
